### ISSUE TITLE
configurator doesn't describe ISR conflicts 

### ISSUE THREAD

**Issue by alexrayne** [renesas/fsp#116] opened 2021-09-06 09:18 UTC
Hallow!
configuring interrupts in FSP configurator, regulary got conflicts on adding new ISR. But conflict message not shows - wich isr are conflict with new one. i have to explore in with some non-trivial, or hard way. 
Expecialy it confuses when conflicts with ISR allocated by stack modules.

IMHO, show - wich ISR are in cinflicts, would be great

**Comment by renesas-brandon-hussey** [comment] 2021-09-07 14:36
Hi @alexrayne can you please provide the following:

1. Which MCU you are using
2. Which FSP version you are using
3. Screenshots or or more information on the issue you are encountering. I am having trouble understanding the issue. I think it is related to conflicts in allocating interrupt slots on a RA2 MCU.

**Comment by alexrayne** [comment] 2021-09-08 06:27
Hallow!
1) work with RA2L1
2) any FSP. latest was v3.2
3) you right - this is about irq slots allocating conflicts. and it looks as
![image](https://user-images.githubusercontent.com/14196732/132457391-26219360-b889-4aa2-9a23-065b9f215e5f.png)
it shows only error mark. no any info - why, wich isr are conflicts.

**Comment by renesas-austin-hansen** [comment] 2024-01-22 22:55
Closing as duplicate of #142

**Closed by renesas-austin-hansen** 2024-01-22 22:55 UTC
