### ISSUE TITLE
FSP5.4 RA8D1 LIN BUG  with uart TX idle state low

### ISSUE THREAD

**Issue by FloHomi** [renesas/fsp#367] opened 2024-07-19 10:10 UTC
Hi,
I discovered a bug in the LIN Library of the FSP 5.4 
The Idle state of the Uart TX is low, but should be hight. There are missing bits in the CCR2 Reg inside r_sci_b_lin.c
see picture for blue line fix:
![image](https://github.com/user-attachments/assets/f1e50bb4-068d-434d-a278-40449a7f1776)

**Comment by renesas-abigail** [comment] 2024-10-08 19:48
Hi @FloHomi,

I am closing this issue as I think the issue was caused by a missing external pull up resistor as described above. If you are still having issues getting it working, feel free to reopen the ticket and add additional information about the hardware setup.

Thanks!

**Closed by renesas-abigail** 2024-10-08 19:48 UTC
Labels: triaged
