### ISSUE TITLE
Problem with bsd socket connect function in file "nx_tcp_client_socket_connect.c"

### ISSUE THREAD

**Issue by swellfox** [renesas/fsp#242] opened 2022-09-22 16:55 UTC
On the Renesas Engineering Community, a potential bug in the RA FSP has been identified:

https://community.renesas.com/mcu-mpu/ra/f/forum/28748/ra6m4---azure-rtos-bsd-socket---fsp-3-8-0---socket-connect-problem

**Comment by jritchey-renesas** [comment] 2022-12-05 15:14
Investigated this and determined that connect was returning the code EINPROGRESS for non-blocking sockets as mentioned in the linked discussion. When looking at the comment header for connect() in nxd_bsd.c, it mentions that connect returns EINPROGRESS to “to distinguish from blocking sockets”. After calling connect, the socket was able to send data correctly. The difference in behavior between FSP and SSP here is likely a result of different versions of NetX Duo.

Closing this since it appears to be expected behavior.

**Closed by jritchey-renesas** 2022-12-05 15:14 UTC
